import type { Trend } from './types';

export const mockTrends: Trend[] = [
  {
    id: '1',
    title: 'Sipping & Swirling Challenge',
    platform: 'tiktok',
    views: 1200000,
    velocity: 95,
    freshness: 2,
    description: 'Users blind taste-test a series of wines and try to guess the varietal and region. The reactions are priceless!',
    imageUrl: 'https://picsum.photos/600/400?random=1',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: '2',
    title: 'Wine & Cheese Board Art',
    platform: 'instagram',
    views: 750000,
    velocity: 80,
    freshness: 5,
    description: 'Visually stunning Reels showcasing the creation of elaborate cheese and charcuterie boards that pair perfectly with specific wines.',
    imageUrl: 'https://picsum.photos/600/400?random=2',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
  },
  {
    id: '3',
    title: 'Quick Sip Reviews',
    platform: 'youtube',
    views: 500000,
    velocity: 70,
    freshness: 1,
    description: 'Fast-paced YouTube Shorts where creators give a 60-second review of a new or interesting wine.',
    imageUrl: 'https://picsum.photos/600/400?random=3',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: '4',
    title: 'DIY Wine Cocktails',
    platform: 'tiktok',
    views: 2100000,
    velocity: 98,
    freshness: 3,
    description: 'Easy-to-follow tutorials for making refreshing wine-based cocktails like spritzers and sangrias.',
    imageUrl: 'https://picsum.photos/600/400?random=4',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
  {
    id: '5',
    title: 'Perfect Pairing Recipes',
    platform: 'instagram',
    views: 980000,
    velocity: 85,
    freshness: 7,
    description: 'Creators share a recipe and the perfect wine to go with it, showing the cooking process and final plating.',
    imageUrl: 'https://picsum.photos/600/400?random=5',
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: '6',
    title: 'Unboxing Wine Subscriptions',
    platform: 'youtube',
    views: 350000,
    velocity: 65,
    freshness: 10,
    description: 'YouTube Shorts showing the unboxing of monthly wine subscription boxes, with first impressions of each bottle.',
    imageUrl: 'https://picsum.photos/600/400?random=6',
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
  },
  {
    id: '7',
    title: 'Guess the Price Point',
    platform: 'tiktok',
    views: 1500000,
    velocity: 92,
    freshness: 4,
    description: 'A fun challenge where creators taste wines and try to guess if they are budget-friendly or luxury bottles.',
    imageUrl: 'https://picsum.photos/600/400?random=7',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
  },
  {
    id: '8',
    title: 'Vino Voyage: Vineyard Tours',
    platform: 'instagram',
    views: 600000,
    velocity: 78,
    freshness: 12,
    description: 'Breathtaking drone shots and walking tours of beautiful vineyards around the world, shared as IG Reels.',
    imageUrl: 'https://picsum.photos/600/400?random=8',
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
  },
];
